// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6zzd0cUCfLs1-pt5EaDaw8DKSyoz-gPk',
    appId: '1:163181736597:web:b0ee0859c3ad7e0b32619c',
    messagingSenderId: '163181736597',
    projectId: 'academyteste-38f0f',
    authDomain: 'academyteste-38f0f.firebaseapp.com',
    storageBucket: 'academyteste-38f0f.firebasestorage.app',
    measurementId: 'G-WDGX6YPWQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQpBkQYRXlzwNzQye0fbDweXyNmDTHEJM',
    appId: '1:163181736597:android:87134d9ddb47ecd332619c',
    messagingSenderId: '163181736597',
    projectId: 'academyteste-38f0f',
    storageBucket: 'academyteste-38f0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqreczTyzMJ5T5Wamg5pCdeh5cvcxLDbQ',
    appId: '1:163181736597:ios:bd23d1334a4b203232619c',
    messagingSenderId: '163181736597',
    projectId: 'academyteste-38f0f',
    storageBucket: 'academyteste-38f0f.firebasestorage.app',
    iosBundleId: 'com.example.appAcademiaTeste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqreczTyzMJ5T5Wamg5pCdeh5cvcxLDbQ',
    appId: '1:163181736597:ios:bd23d1334a4b203232619c',
    messagingSenderId: '163181736597',
    projectId: 'academyteste-38f0f',
    storageBucket: 'academyteste-38f0f.firebasestorage.app',
    iosBundleId: 'com.example.appAcademiaTeste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6zzd0cUCfLs1-pt5EaDaw8DKSyoz-gPk',
    appId: '1:163181736597:web:21d5edf9292270ab32619c',
    messagingSenderId: '163181736597',
    projectId: 'academyteste-38f0f',
    authDomain: 'academyteste-38f0f.firebaseapp.com',
    storageBucket: 'academyteste-38f0f.firebasestorage.app',
    measurementId: 'G-BGFSM1QFT8',
  );
}
